# Settings for the app
app:
  # HTML Title
  title: Polygons in Shareabouts
  # Header name
  name: Parking Lots of Brooklyn
  # Meta description that will show up in Google search results
  meta_description: _(The top 150 parking lots of Kings County, NY.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.65
      lng: -73.95
    zoom: 14
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-w29s5fls/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
place_types:
  "10":
    label: _(Landmark)
    rules:
      - condition: '"{{location_type}}" === "10" && {{submission_sets.comments.length}} > 0'
        style:
          color: '#f9ff00'
          weight: 3
          opacity: 0.7
          fillOpacity: 0.7
        focus_style:
          color: '#CD95D7'
          weight: 3
          opacity: 0.9
          fillOpacity: 0.5
      - condition: '"{{location_type}}" === "10"'
        style:
          color: '#f9ff6a'
          weight: 2
          opacity: 0.7
          fillOpacity: 0.3
        focus_style:
          color: '#CD95D7'
          weight: 3
          opacity: 0.9
          fillOpacity: 0.5

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: false
  add_button_label: _(Add a Place)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(Location Type)
      type: select
      options:
        - label: _(Landmark)
          value: landmark
        - label: _(Park)
          value: park
        - label: _(School)
          value: school
      name: location_type
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
